layout: sidebar
style: dark
# layout: stacked
# layout: default
# style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: 
    - pushed
  limit: 6
  exclude:
    archived: true
    forks: false
    projects:
    - personal-website
    - achlys-description
    - terlplate
    # - ballgame
  # sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars

social_media:
  twitter: IKopest
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://ikopest.me
  # youtube: your_username

topics:
  - name: Erlang/OTP
    web_url: https://github.com/erlang/otp
    image_url: http://erlang.org/doc/erlang-logo.png

  - name: Distributed Systems

  - name: GRiSP
    web_url: https://grisp.org
    image_url: https://github.com/Laymer/personal-website/raw/master/assets/grisp400x400.png

  - name: Elixir
    web_url: https://elixir-lang.org
    image_url: https://elixir-lang.org/images/logo/logo.png
